name: yourseatgraduationproject
description: "A new Flutter project."
publish_to: "none" # Prevents accidental publishing to pub.dev.

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  bot_toast: ^4.1.3
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.4.3
  cupertino_icons: ^1.0.6
  curved_labeled_navigation_bar: ^2.0.2
  dartz: ^0.10.1
  http: ^1.3.0
  pdf_render: ^1.4.7
  dio: ^5.8.0+1
  equatable: ^2.0.5
  firebase_app_check: ^0.3.1+4
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.2
  file_picker: ^5.2.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_facebook_auth: null
  flutter_localization: ^0.2.2
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: null
  get_it: ^8.0.1
  google_fonts: ^6.2.1
  google_sign_in: null
  hive_flutter: ^1.1.0
  html: ^0.15.5
  intl_utils: ^2.8.7
  otp_pin_field: ^1.3.1

dev_dependencies:
  data_table_2: ^2.5.6

  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

    - assets/icons/

    -  assets/pdf/contract.pdf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Manrope
  #     fonts:
  #       - asset: assets/fonts/Manrope-Regular.ttf
  #   - family: GE Dinar One
  #     fonts:
  #       - asset: assets/fonts/GE-Dinar-One-Medium.otf
  #   #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
