// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA16oAC-HIySE4A1xLpQ956AT-z5ElHk8w',
    appId: '1:556627768143:web:cf1a2ff424bb4935b5cb3a',
    messagingSenderId: '556627768143',
    projectId: 'yourseatgraduationprojec-19068',
    authDomain: 'yourseatgraduationprojec-19068.firebaseapp.com',
    storageBucket: 'yourseatgraduationprojec-19068.appspot.com',
    measurementId: 'G-0HELS1X1W8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCREJCsFWlgq_kon3J8_Eu_mhvL0PUNGjs',
    appId: '1:556627768143:android:f217ff5d7d11f450b5cb3a',
    messagingSenderId: '556627768143',
    projectId: 'yourseatgraduationprojec-19068',
    storageBucket: 'yourseatgraduationprojec-19068.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_8dKCT7vsUK4YAUIGHSl8FU2wUi5QhXA',
    appId: '1:556627768143:ios:263239cdf600ebe7b5cb3a',
    messagingSenderId: '556627768143',
    projectId: 'yourseatgraduationprojec-19068',
    storageBucket: 'yourseatgraduationprojec-19068.appspot.com',
    iosBundleId: 'com.example.yourseatgraduationproject',
  );
}
